
CREATE TABLE `wp_rnb_courses` (
  `ncourse_id` int(11) NOT NULL,
  `vcourse_title` varchar(50) NOT NULL,
  `ncourse_order` int(11) NOT NULL,
  `ncategory_id` int(11) NOT NULL,
  `vslug` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

INSERT INTO `wp_rnb_courses` (`ncourse_id`, `vcourse_title`, `ncourse_order`, `ncategory_id`, `vslug`) VALUES
(1, 'english literature', 1, 1, 'english-literature'),
(2, 'home science', 1, 1, 'home-science'),
(3, 'music', 1, 1, 'music'),
(4, 'botany', 1, 2, 'botany'),
(5, 'chemistry', 1, 2, 'chemistry'),
(6, 'physics', 1, 2, 'physics'),
(7, 'zoology', 1, 2, 'zoology'),
(8, 'economics', 1, 3, 'economics'),
(9, 'civil engineering', 1, 4, 'civil-engineering'),
(10, 'computer science', 1, 4, 'computer-science'),
(11, 'geography', 1, 5, 'geography'),
(12, 'history', 1, 5, 'history'),
(13, 'physical education', 1, 5, 'physical-education'),
(14, 'political science', 1, 5, 'political-science'),
(15, 'psycology', 1, 5, 'psycology'),
(16, 'sociology', 1, 5, 'sociology'),
(17, 'biotechnology', 1, 6, 'biotechnology'),
(18, 'microbiology', 1, 6, 'microbiology'),
(19, 'management', 1, 7, 'management'),
(20, 'forensic science', 1, 8, 'forensic-science'),
(21, 'library science', 1, 8, 'library-science'),
(22, 'nursing', 1, 8, 'nursing'),
(23, 'soil science', 1, 8, 'soil-science'),
(24, 'education', 1, 9, 'education'),
(25, 'mathematics', 1, 10, 'mathematics'),
(26, 'pharmacy', 1, 11, 'pharmacy'),
(27, 'physiotherapy', 1, 12, 'physiotherapy'),
(32, 'dentistry', 1, 13, 'dentistry'),
(33, 'environmental science', 1, 8, 'environmental-science'),
(34, 'journalism', 1, 5, 'journalism'),
(35, 'ayurveda', 1, 13, 'ayurveda'),
(36, 'Plant Pathology', 1, 6, 'plant-pathology'),
(37, 'Marketing', 1, 7, 'marketing'),
(38, 'Food Science', 1, 8, 'food-science'),
(39, 'Social Science', 1, 5, 'social-science'),
(40, 'Fashion Technology', 1, 1, 'fashion-technology'),
(41, 'Law', 1, 5, 'law'),
(42, 'Agriculture', 1, 5, 'agriculture'),
(43, 'Organic farming', 1, 14, 'organic-farming');
