
CREATE TABLE `wp_rnb_universities` (
  `nuniversity_id` int(11) NOT NULL,
  `vuniversity_title` varchar(200) NOT NULL,
  `nuniversity_order` int(11) NOT NULL,
  `vslug` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

INSERT INTO `wp_rnb_universities` (`nuniversity_id`, `vuniversity_title`, `nuniversity_order`, `vslug`) VALUES
(1, 'Dr. A. P. J. Abdul Kalam University, Indore', 1, 'drapjabdulkalam-university-indore'),
(2, 'Arunanchal University ', 2, 'arunachalpradesh-university'),
(3, 'Baba Mastnath University ', 3, 'baba-mastnath-university'),
(4, 'Banasthali University ', 4, 'banasthali-university'),
(5, 'Career Point University, Kota', 5, 'career-point-university-kota'),
(6, 'Cmj University, Meghalaya', 6, 'cmj-university-meghalaya'),
(7, 'Dev Sanskriti University, Gayatrikunj-Shantikunj Haridwar', 7, 'dev-sanskriti-university'),
(8, 'Himalayan Garhwal University, Shiv Nagar, Phokra, Pauri Garhwal-246169, Uttarakhand', 8, 'himalayan-garhwal-university'),
(9, 'Himalayan University, Itanagar', 9, 'himalayan-university'),
(10, 'Kalinga University, Naya ,Raipur', 10, 'kalinga-university-raipur'),
(11, 'Lnct University, Bhopal (M.P.)', 11, 'lnct-university-bhopal-mp'),
(12, 'Lord University, Alwar-Bhiwadi, Delhi', 12, 'lord-university-alwar-bhiwadi-delhi'),
(13, 'Mansarowar Global University, Sehore (M.P.)', 13, 'mansarowar-global-university-sehore-mp'),
(14, 'Mewar University, Chittorgarh', 14, 'mewar-university-chittorgarh'),
(15, 'Muit University , Lucknow', 15, 'muit-university-lucknow'),
(16, 'Mvgu University, Jaipur (Rajasthan)', 17, 'mvgu-university-jaipur-rajasthan'),
(17, 'Opjs University, Churu, (Rajasthan)', 18, 'opjs-university-churu-rajasthan'),
(18, 'Raffles University ,Neemrana, Alwar, (Rajasthan)', 19, 'raffles-university-neemrana-alwar-rajasthan'),
(19, 'Ravindranath Tagore University, (Madhya Pradesh)', 20, 'ravindranath-tagore-university-madhya-pradesh'),
(20, 'Sardar Patel University, Balaghat, (M.P.)', 21, 'sardar-patel-university-balaghat-mp'),
(21, 'Shri Kaushal Das (Skd) University, Hanumangarh, Rajasthan', 22, 'shri-kaushal-das-skd-university-hanumangarh-rajasthan'),
(22, 'Shridhar University, Pilani, Rajasthan', 23, 'shridhar-university-pilani-rajasthan'),
(23, 'Shyam University, Dausa, Rajasthan', 24, 'shyam-university-dausa-rajasthan'),
(24, 'Singhania University, Pacheri Bari, Jhunjhunu (Rajasthan)', 25, 'singhania-university-pacheri-bari-jhunjhunu-rajasthan'),
(25, 'Shri Krishna University, Chhatarpur (M.P.)', 26, 'shri-krishna-university-chhatarpur-mp'),
(26, 'Sri Satya Sai University, Of Technology & Medical Sciences, Sehore', 26, 'sri-satya-sai-university-of-technology-and-medical-sciences-sehore'),
(27, 'Sunrise University, Alwar, (Rajasthan)', 27, 'sunrise-university-alwar-rajasthan'),
(28, 'Uot University, Jaipur, (Rajasthan)', 28, 'uot-university-jaipur-rajasthan'),
(29, 'Shri Venkateshwara  University, (Uttar Pradesh)', 29, 'shri-venkateshwara-university-uttar-pradesh'),
(30, 'Ybn University, Numkum, Ranchi', 30, 'ybn-university-numkum-ranchi'),
(31, 'Lovely Professional University', 31, 'lovely-professional-university'),
(32, 'Rani Durgawati Vishwavidyalaya, Jabalpur, MP', 32, 'rani-durgawati-vishwavidyalaya-jabalpur-mp'),
(33, 'Guru Govind Singh Indraptrastha University, New Delhi', 33, 'guru-govind-singh-indraptrastha-university-new-delhi'),
(34, 'ICFAI University, Jharkhand', 34, 'icfai-university-jharkhand'),
(35, 'Maharaja Surajmal Brij University, Bharatpur', 35, 'maharaja-surajmal-brij-university-bharatpur'),
(36, 'Maharishi Dayanand Saraswati University, Ajmer', 36, 'maharishi-dayanand-saraswati-university-ajmer'),
(37, 'Manonmaniam Sundaranar University, Tirunelveli', 37, 'manonmaniam-sundaranar-university-tirunelveli'),
(38, 'Venkateshwara Open University', 38, 'venkateshwara-open-university'),
(39, 'G H Raisoni University Saikheda', 39, 'gh-raisoni-university-saikheda'),
(40, 'Starex University', 40, 'starex-university'),
(41, 'Kumaun University Nainital, Uttarakhand', 41, 'kumaun-university-nainital-uttarakhand'),
(42, 'SRM Institute of Science and Technology', 1, 'srm-institute-of-science-and-technology'),
(43, 'IIT INDORE', 43, 'iit-indore'),
(44, 'Shoolini University', 44, 'shoolini-university'),
(45, 'Rani Durgavati University', 1, 'rani-durgavati-university'),
(46, 'Mohanlal Sukhadia University', 1, 'mohanlal-sukhadia-university'),
(47, 'DR. B.R. AMBEDKAR UNIVERSITY, DELHI', 1, 'dr-br-ambedkar-university-delhi'),
(48, 'Alagappa University', 1, 'alagappa-university'),
(49, 'Tantia University, Sriganganagar ( Rajasthan)', 1, 'tantia-university-sriganganagar--rajasthan'),
(50, 'Peoples University, Bhopal ( MP )', 1, 'peoples-university-bhopal--mp-'),
(51, ' Desh Bhagat University, Mandi Gobindgarh, Punjab', 1, '-desh-bhagat-university-mandi-gobindgarh-punjab'),
(52, ' Bharathi Vidyapeeth University, Pune', 1, '-bharathi-vidyapeeth-university-pune'),
(53, 'IIT BOMBAY', 1, 'iit-bombay'),
(54, ' Manonmaniam Sundaranar University', 1, '-manonmaniam-sundaranar-university'),
(55, 'GH Raisoni University Saikheda', 1, 'gh-raisoni-university-saikheda');
